#!/usr/bin/env php
<?php

if (count($argv) === 1) {
	echo "Missing source directory parameter\n";
	exit(2);
}
$src = substr($argv[1], -1) == '/'
	? substr($argv[1], 0, -1)
	: $argv[1];

define('WORK_DONE', "{$src}_DONE_" . time());
if (!file_exists($src)) {
	echo "Directory provided is not accessible\n";
	exit(3);
}

exec("/usr/bin/find {$src} -type f", $lines);
$total = $current = count($lines);

if (!mkdir(WORK_DONE)) {
	echo "Cannot create output directory\n";
	exit(4);
}

process($src);
system('clear');
echo PHP_EOL . "Done! See " . WORK_DONE . PHP_EOL;


function getName($source) {
	return preg_replace('/[^a-zA-Z0-9_]/', '', $source);
}


function process($loc, $name = '') {
	global $total, $current;
	foreach (new DirectoryIterator($loc) as $fileInfo) {
		if ($fileInfo->isDot()) {
			continue;
		}
		if ($fileInfo->isDir()) {
			$dirName = $fileInfo->getFilename();
			process("{$loc}/{$dirName}", $name ? "{$name}_{$dirName}" : $dirName);
			continue;
		}
		$ext = $fileInfo->getExtension();
		$prevName = $fileInfo->getBaseName(".{$ext}");
		$newName = WORK_DONE . "/" . getName($name) . "_" . getName($prevName);

		if (file_exists("$newName.$ext")) {
			$newName .= '-' . md5(time());
		}

		$res = copy("{$loc}/{$prevName}.{$ext}", "{$newName}.{$ext}");
		if (!$res) {
			echo "\nError: Cannot copy file {$newName}.\n";
			exit(5);
		}
		system('clear');
		$curr = ($total - --$current);

		echo "Processing " . progress($curr) . ' ' . (int)($curr / $total * 100) . '%';
	}
}


function progress($modMe) {
	$rotate = array('', '|', '/', '-', '\\');
	return $rotate[$modMe % 5];
}
