#!/usr/bin/env php
<?php
include(__DIR__ . '/Flattener.php');

if (count($argv) === 1) {
    err("Missing mandatory source directory parameter", 2);
}
$src = realpath($argv[1]);
if (!$src) {
    err("The directory provided is not accessible", 3);
}

try {
    $time = -microtime(true);               // no progress bar for windows
    $fl = new helvete\Tools\Flattener($src, DIRECTORY_SEPARATOR !== '\\');
    $fl->transmogrify();
    $time += microtime(true);
    $time = number_format($time, 2);
    echo PHP_EOL . "Processed {$fl->getTot()} files in {$time} sec. using "
        . memory_get_peak_usage(true) / 1024 . "kB memory" . PHP_EOL;
} catch (Exception $e) {
    err($e->getMessage(), $e->getCode());
}

function err($msg = '', $exitCode = 127) {
    echo "ERROR: $msg" . PHP_EOL;
    exit($exitCode);
}
